- openwrt-addons/etc/init.d/set_etc_hardware
- openwrt-build/apply_profile.code
> Korrekter Patch für #63

- openwrt-build/apply_profile.code
- openwrt-build/build_release.sh
- IPSYSTEM aus `apply_profile.code.definitions` mit ffweimar als default - siehe #69 
- kleinere Sicherheitschecks, falls beim checkout was schiefgeht - siehe #65 
- https://github.com/weimarnetz/weimarnetz/commit/bef6ae2f9ec10bc1a983f954769145ac2118848f kann ich mir grad nicht erklären, weiß nicht was git da gemacht hat. In der Summe wird die Datei aber nicht verändert, kommt wohl vom Merge.
> fix #69 and add checks in buildsystem as discussed in #65

- openwrt-addons/etc/kalua/vpn
- openwrt-build/apply_profile.code
Hallo, 
hier ein getesteter Patch wegen #67 (VPN Script und jshn.sh) 
Und noch ein Typo-Fix im letzten Pull-Request für #69 
Neue Features: Es wird jetzt automatisch das VPN mit dem kleinsten Ping genommen! Siehe Zeile 282...etwas schmutzig, aber läuft. Kann man auch noch ändern, das zufällig Server genommen werden etc.pp
> VPN Script 

- openwrt-build/apply_profile.code
Example for not deleting entries we don't want to control
> set dhcp config using uci

- openwrt-addons/etc/kalua/cron
- openwrt-addons/etc/kalua/file
- openwrt-addons/etc/kalua/olsr
- openwrt-addons/etc/kalua/stopwatch
- openwrt-addons/etc/kalua/vpn
Ich hab mal das alles von Basti übernommen, was wir brauchen, um Kalua auch auf einem Debian-Server laufen zu lassen. Dort wird dann vtun und olsr gestartet und konfiguriert.
Bitte guckt auch mal, ob das normale Router nicht weiter stört
> Ergänzungen für Server-VPN-Scripts

- openwrt-build/apply_profile.code
> fix forced https redirect on splash page

- README.md
- TODO.txt
- openwrt-addons/etc/dhcp-script.d/10dhcpscript
- openwrt-addons/etc/init.d/S41build_static_netparam
- openwrt-addons/etc/init.d/S43ethers_fff+
- openwrt-addons/etc/init.d/S69watch_olsrd_fff+
- openwrt-addons/etc/init.d/S70prepare_fff+
- openwrt-addons/etc/init.d/crashlog_apport
- openwrt-addons/etc/init.d/generate_kalua_loader
- openwrt-addons/etc/kalua/firmware
- openwrt-addons/etc/kalua/links
- openwrt-addons/etc/kalua/log
- openwrt-addons/etc/kalua/ntp
- openwrt-addons/etc/kalua/software
- openwrt-addons/etc/kalua/switch
- openwrt-addons/etc/kalua/vpn
- openwrt-addons/etc/kalua/watch
- openwrt-addons/etc/kalua/weblogin
- openwrt-addons/etc/kalua/wifi
- openwrt-addons/etc/kalua_init.user
- openwrt-addons/etc/variables_software_fff+
- openwrt-addons/usr/bin/scheduler
- openwrt-addons/usr/sbin/cron.check_inet_gw_fff+
- openwrt-addons/usr/sbin/cron.minutely
- openwrt-addons/usr/sbin/cron.olsr-hna-slave
- openwrt-build/rc.local
Done via `find -type f -not -iwholename "*.git*" -exec sed -i 's|uci get|uci -q get|g' "{}" \;`
> replaced all `uci get` calls with `uci -q get`, to avoid error printings

- openwrt-addons/etc/kalua/vpn
requires 
`CONFIG_BUSYBOX_CONFIG_SHUF=y`
> randomize vpn selection

- openwrt-addons/etc/kalua/wget
kalua: wget: minor fixes for making 'shellsheck' more happy
> kalua: wget: minor fixes for making 'shellsheck' more happy

- openwrt-addons/etc/profile.d/kalua.sh
while we are at it, fix a bug in password != good detection
> profile.d: login via ssh: show reboot reason

- openwrt-addons/etc/kalua_init
- openwrt-addons/etc/kalua_init.user
> kalua: loader - minor fixes (e.g. for shellsheck)

- openwrt-build/apply_profile.code
not only partially
now on Gebrannte Mandeln
> delete dhcp option 121

- openwrt-build/apply_profile.code
> kompromiss für beacon intervall

- openwrt-addons/etc/kalua/vpn
> _vpn needed didn't return 0

- openwrt-addons/etc/kalua/watch
> kalua: watch: vpn_server_is_neigh() fix check

- Makefile
> don't copy regulatory.bin into image

- openwrt-addons/etc/kalua/sanitizer
> sync _sanitizer with kalua

- openwrt-addons/etc/dhcp-script.d/10dhcpscript
- openwrt-addons/etc/init.d/S43ethers_fff+
- openwrt-addons/etc/init.d/crashlog_apport
- openwrt-addons/etc/kalua/cron
- openwrt-addons/etc/kalua/firmware
- openwrt-addons/etc/kalua/ipsystem
- openwrt-addons/etc/kalua/links
- openwrt-addons/etc/kalua/netfilter
- openwrt-addons/etc/kalua/ntp
- openwrt-addons/etc/kalua/nvram
- openwrt-addons/etc/kalua/software
- openwrt-addons/etc/kalua/vpn
- openwrt-addons/etc/kalua/weblogin
- openwrt-addons/etc/kalua_init.user
- openwrt-addons/etc/kalua_init.user_fake_missing_uci
- openwrt-addons/etc/variables_software_fff+
- openwrt-addons/usr/sbin/cron.registrator_client.sh
> use unique config sections from uci

- openwrt-addons/etc/kalua/netfilter
> Update NOTRACK syntax

- openwrt-addons/etc/kalua_init
- openwrt-addons/etc/kalua_init.user
- openwrt-addons/etc/kalua_init.user_fake_missing_uci
avoid double inclusion of /etc/profile.d/kalua.sh
fixes #204
> kalua: loader: sync with upstream

- openwrt-build/apply_profile.code
> add restrict_local=1 to apply_profile.code

- openwrt-addons/etc/kalua/vpn
> remove ping from vpn check

- openwrt-addons/etc/init.d/S12switch_etx
- openwrt-addons/etc/init.d/S43ethers_fff+
- openwrt-addons/etc/init.d/S51crond_fff+
- openwrt-addons/etc/init.d/set_etc_hardware
> init.d-scipts: remove superflous spaces

- openwrt-build/apply_profile.code
zram is broken at the moment https://github.com/weimarnetz/weimarnetz/issues/251
> disable zram (GebrannteMandeln)

- openwrt-build/apply_profile.code
zram is broken at the moment - https://github.com/weimarnetz/weimarnetz/issues/251
> disable zram

- openwrt-addons/etc/dhcp-script.d/10dhcpscript
- openwrt-addons/etc/kalua/netfilter
mögliche Lösung für das Problem von zuwenig IP-Adressen.
> fix sticky arp entries

- openwrt-addons/etc/kalua/ssh
> sync _ssh with kalua

- openwrt-build/apply_profile.code
alt: weimarnetz 
neu: ff.intern.23.a für 5ghz und knoten 23
ff.intern.23.g für 2.4ghz und knoten 23
> change adhoc ssid

- openwrt-build/apply_profile.code
der krumme wert 375 macht glaub ich probleme, das default tut keinem weh.
> use default beacon int

- openwrt-addons/etc/kalua/scheduler
- openwrt-addons/etc/kalua/ssh
- openwrt-addons/usr/bin/scheduler
- openwrt-addons/usr/sbin/cron.minutely
fixes #252 
cron.taskplanner.default fehlt hier, weil zu viele abhängigkeiten von anderen kalua scripten. 
ist auch erstmal crash&burn - ungetestet.
> sync _scheduler with kalua

- files/etc/kalua/vpn
doing 3 steps in one leads to wrong results (no valid answer received). So assignment and test were split up
> improve server status query
